/**
 *  Given two strings s and t which consist of only lowercase letters.

 String t is generated by random shuffling string s and then add one more letter at a random position.

 Find the letter that was added in t.
 */
public class FindTheDifference {
    public char findTheDifference(String s, String t) {
       int AsciiSum=0;
        for (int i = 0; i <t.length() ; i++) {
            AsciiSum+=t.charAt(i);
        }
        for (int i = 0; i <s.length() ; i++) {
            AsciiSum-=s.charAt(i);
        }
        return (char) AsciiSum;


    }


    public static void main(String[] args){
        FindTheDifference f = new FindTheDifference();
        System.out.print(f.findTheDifference("abASDASDASDced","abgASDASDced"));
    }
}
